-- add_requires("glap")
add_requires("yaml-cpp")
add_requires("tl_expected")
add_requires("fmt")

target("mmg")
    set_kind("binary")
    set_basename("mmg")
    set_languages("cxx20")
    add_files("src/**.cpp")
    add_includedirs("include")
    add_packages("yaml-cpp", "fmt", "tl_expected")
    add_deps("glap")
    -- add_rules("glap.mmg")
    -- add_files("mmg/args.glap.yml")
